In [5]:
import pandas as pd
import numpy as np

In [6]:
data=pd.read_csv('../00_DATA/final_dataset.csv')

In [7]:
data['startYear']=data['startYear'].astype(int)
data

,tconst,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes,Adult,Animation,Fantasy,Game-Show,...,News,Reality-TV,Sci-Fi,Short,Sport,Talk-Show,War,Western,averageRating,numVotes
0,tt0035423,Kate & Leopold,Kate & Leopold,0,2001,118,0,0,1,0,...,0,0,0,0,0,0,0,0,6.4,81936.0
1,tt0036177,Muhomatsu no issho,Muhomatsu no issho,0,2008,100,0,0,0,0,...,0,0,0,0,0,0,0,0,7.3,113.0
2,tt0062336,The Tango of the Widower and Its Distorting Mi...,El Tango del Viudo y Su Espejo Deformante,0,2020,70,0,0,0,0,...,0,0,0,0,0,0,0,0,6.3,157.0
3,tt0065392,Bucharest Memories,Amintiri bucurestene,0,2020,\N,0,0,0,0,...,0,0,0,0,0,0,0,0,7.4,12.0
4,tt0069049,The Other Side of the Wind,The Other Side of the Wind,0,2018,122,0,0,0,0,...,0,0,0,0,0,0,0,0,6.8,6930.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147377,tt9915872,The Last White Witch,My Girlfriend is a Wizard,0,2019,97,0,0,1,0,...,0,0,0,0,0,0,0,0,7.7,7.0
147378,tt9916170,The Rehearsal,O Ensaio,0,2019,51,0,0,0,0,...,0,0,0,0,0,0,0,0,7.2,5.0
147379,tt9916190,Safeguard,Safeguard,0,2020,90,0,0,0,0,...,0,0,0,0,0,0,0,0,3.6,226.0
147380,tt9916362,Coven,Akelarre,0,2020,92,0,0,0,0,...,0,0,0,0,0,0,0,0,6.4,4085.0
147381,tt9916428,The Secret of China,Hong xing zhao yao Zhong guo,0,2019,\N,0,0,0,0,...,0,0,0,0,0,0,1,0,3.8,14.0

In [14]:
# keeping titles from 2000 and above only
data = data[data['startYear'] >= 2000]
titles = data['primaryTitle']
titles

0                                            Kate & Leopold
1                                        Muhomatsu no issho
2         The Tango of the Widower and Its Distorting Mi...
3                                        Bucharest Memories
4                                The Other Side of the Wind
                                ...
147377                                 The Last White Witch
147378                                        The Rehearsal
147379                                            Safeguard
147380                                                Coven
147381                                  The Secret of China
Name: primaryTitle, Length: 131682, dtype: object

In [9]:
# how many movies after 2000 are there?
len(titles)

131682

# Practice Run - no need to run this cell

In [2]:
# PRACTICE API CALL FOR ONE HARDCODED MOVIE: "THE DARK KNIGHT"
import tmdbsimple as tmdb

# Clem's API key
tmdb.API_KEY = 'f6553225b3b37ae2a29dad9a832393d9'

# In case clem's doesn't work, you can use mine (louis)
# tmdb.API_KEY = 'ae28396bb24c53a5d6b8a64a0ac95bf8'

search = tmdb.Search()

# First request to get the movie's IMDB id based on its title
response1 = search.movie(query="The Dark Knight")
movie_id = response1['results'][0]['id']

# Second request to get all the information about the movie using the id
movie = tmdb.Movies(movie_id)
movie_info = movie.info()

# The information we need to save for the project:
budget = movie_info['budget']
revenue = movie_info['revenue']
movie_id # so we can easily re-access the API if needed

{'adult': False,
 'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
 'belongs_to_collection': {'id': 263,
  'name': 'The Dark Knight Collection',
  'poster_path': '/l4T8JVwircGZlZuSl29U3TS9mpl.jpg',
  'backdrop_path': '/xfKot7lqaiW4XpL5TtDlVBA9ei9.jpg'},
 'budget': 185000000,
 'genres': [{'id': 18, 'name': 'Drama'},
  {'id': 28, 'name': 'Action'},
  {'id': 80, 'name': 'Crime'},
  {'id': 53, 'name': 'Thriller'}],
 'homepage': 'https://www.warnerbros.com/movies/dark-knight/',
 'id': 155,
 'imdb_id': 'tt0468569',
 'original_language': 'en',
 'original_title': 'The Dark Knight',
 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
 'popularity': 53.904,
 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
 'production_companies': [{'id': 429,
   'logo_path': '/2Tc1P3Ac8M479naPp1kYT3izLS5.png',
   'name': 'DC Comics',
   'origin_country': 'US'},
  {'id': 923,
   'logo_path': '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png',
   'name': 'Legendary Pictures',
   'origin_country': 'US'},
  {'id': 9996,
   'logo_path': '/3tvBqYsBhxWeHlu62SIJ1el93O7.png',
   'name': 'Syncopy',
   'origin_country': 'GB'},
  {'id': 118865,
   'logo_path': None,
   'name': 'Isobel Griffiths',
   'origin_country': 'GB'},
  {'id': 9993,
   'logo_path': '/2Tc1P3Ac8M479naPp1kYT3izLS5.png',
   'name': 'DC Entertainment',
   'origin_country': 'US'},
  {'id': 174,
   'logo_path': '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
   'name': 'Warner Bros. Pictures',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'GB', 'name': 'United Kingdom'},
  {'iso_3166_1': 'US', 'name': 'United States of America'}],
 'release_date': '2008-07-14',
 'revenue': 1004558444,
 'runtime': 152,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'},
  {'english_name': 'Mandarin', 'iso_639_1': 'zh', 'name': '普通话'}],
 'status': 'Released',
 'tagline': 'Why So Serious?',
 'title': 'The Dark Knight',
 'video': False,
 'vote_average': 8.5,
 'vote_count': 26242}

# Real loop

Includes:
- a try/except structure to avoid the code to crash if the movie id is not found
- a safety backup to CSV every 1000 movie, just in case
- stores the IMDB id, movie title (for visual clue), budget, and revenue
- If the stored revenue is 0, it is not published on IMDB
- If the stored revenue is -1, the movie was not found on IMDB

In [24]:
# FULL LOOP - THIS IS THE IMPORTANT CELL! 

api_results = []

import tmdbsimple as tmdb
tmdb.API_KEY = 'f6553225b3b37ae2a29dad9a832393d9'
search = tmdb.Search()

for index, movie_title in enumerate(titles[0:10]): # for a test run, replace this line by: for movie_title in titles[0:50]
    
    print("Fetching movie number", index + 1, "out of", len(titles), '...')
    response = search.movie(query=movie_title)
    
    try:
        movie_id = response['results'][0]['id']
        movie = tmdb.Movies(movie_id)
        movie_info = movie.info()
        budget = movie_info['budget']
        revenue = movie_info['revenue']
        
        print("Title:", movie_title)
        print("Budget:", budget)
        print("Revenue:", revenue)
        
    except:
        movie_id, budget, revenue = -1, -1, -1
        print("movie not found in API")
        
    
    # saving results to the api_results dataframe:
    api_results.append({'title': movie_title, 'imdb_id': movie_id, 'budget': budget, 'revenue': revenue})
    
    # saves the data to a CSV every "save_frequency". Feel free to change the value
    save_frequency = 8
    if (index + 1) % save_frequency == 0:
        save_df = pd.DataFrame(api_results)
        save_df.to_csv('api_backup.csv')
        print("***Current movies saved to a CSV.***")
    
    print("\n")

Fetching movie number 1 out of 131682 ...
Title: Kate & Leopold
Budget: 48000000
Revenue: 76019048


Fetching movie number 2 out of 131682 ...
Title: Muhomatsu no issho
Budget: 0
Revenue: 0


Fetching movie number 3 out of 131682 ...
Title: The Tango of the Widower and Its Distorting Mirror
Budget: 0
Revenue: 0


Fetching movie number 4 out of 131682 ...
Title: Bucharest Memories
Budget: 0
Revenue: 0


Fetching movie number 5 out of 131682 ...
Title: The Other Side of the Wind
Budget: 12000000
Revenue: 0


Fetching movie number 6 out of 131682 ...
Title: The Naked Monster
Budget: 350000
Revenue: 0


Fetching movie number 7 out of 131682 ...
Title: Grizzly II: Revenge
Budget: 7500000
Revenue: 0


Fetching movie number 8 out of 131682 ...
Title: Crime and Punishment
Budget: 0
Revenue: 0
***Current movies saved to a CSV.***


Fetching movie number 9 out of 131682 ...
Title: The Wandering Soap Opera
Budget: 0
Revenue: 0


Fetching movie number 10 out of 131682 ...
movie not found in API

In [26]:
# If the loop finishes, you can inspect the full output here:

# print(api_results)




# or here:

# output = pd.DataFrame(api_results)




# if the loop fully worked, make sure to save it one last time to CSV:

# output = pd.DataFrame(api_results)
# output.to_csv('api_backup.csv')

                                               title  imdb_id    budget  \
0                                     Kate & Leopold    11232  48000000
1                                 Muhomatsu no issho   895979         0
2  The Tango of the Widower and Its Distorting Mi...   602986         0
3                                 Bucharest Memories   741942         0
4                         The Other Side of the Wind   299782  12000000
5                                  The Naked Monster    29163    350000
6                                Grizzly II: Revenge    38258   7500000
7                               Crime and Punishment   109809         0
8                           The Wandering Soap Opera   467254         0
9                         West from North Goes South       -1        -1

    revenue
0  76019048
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9        -1