In [21]:
import pandas as pd

In [22]:
data=pd.read_csv('revenue_actors.csv')

In [23]:
data

,Unnamed: 0,tconst,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes,Adult,Animation,Fantasy,...,Sport,Talk-Show,War,Western,averageRating,numVotes,budget,revenue,isTopActor,isTopDirector
0,0,tt0035423,Kate & Leopold,Kate & Leopold,0,2001,118,0,0,1,...,0,0,0,0,6.4,81936.0,48000000,76019048,True,False
1,5062,tt0116391,Gang,Gang,0,2000,152,0,0,0,...,0,0,0,0,6.2,236.0,30000000,41480851,False,False
2,5778,tt0118589,Glitter,Glitter,0,2001,104,0,0,0,...,0,0,0,0,2.3,23292.0,22000000,5271666,False,False
3,6540,tt0120166,The Sorcerer's Apprentice,The Sorcerer's Apprentice,0,2001,86,0,0,1,...,0,0,0,0,4.5,565.0,150000000,215283742,False,False
4,6682,tt0120467,Vulgar,Vulgar,0,2000,87,0,0,0,...,0,0,0,0,5.2,4078.0,120000,14904,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8055,147181,tt9872052,Eight,Eight,0,2018,88,0,0,0,...,0,0,0,0,7.7,9.0,70000000,297718711,False,False
8056,147192,tt9875554,Alaska,Alaska,0,2019,72,0,0,0,...,0,0,0,0,6.2,20.0,23000000,11829959,False,False
8057,147224,tt9883996,Dream Horse,Dream Horse,0,2020,113,0,0,0,...,0,0,0,0,6.9,2919.0,20000000,6435260,False,False
8058,147263,tt9892546,Aladdin,Aladdin,0,2020,104,0,0,0,...,0,0,0,0,3.8,26.0,183000000,1047612394,False,False
8059,147334,tt9904802,Enemy Lines,Enemy Lines,0,2020,92,0,0,0,...,0,0,1,0,4.5,1432.0,40000000,91753202,False,False

In [33]:
#data_budget=data[(data['revenue']<10000) | (data['budget']<10000)]
data.drop(data[(data['revenue']<10000) | (data['budget']<10000)].index, inplace = True)
data.to_csv('final_filtered_data.csv')

In [13]:

        data_budget['budget'][i]=data_budget['budget'][i]*100000
    else
#data_budget['revenue']=data_budget['revenue']*1000000

/var/folders/4b/9yr63vtn00bfj8vq0m8bphhw0000gn/T/ipykernel_26410/3154635723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_budget['budget']=data_budget['budget']*1000000

In [14]:
data_budget

,Unnamed: 0,tconst,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes,Adult,Animation,Fantasy,...,Sport,Talk-Show,War,Western,averageRating,numVotes,budget,revenue,isTopActor,isTopDirector
39,8411,tt0144084,American Psycho,American Psycho,0,2000,101,0,0,0,...,0,0,0,0,7.6,533604.0,6000000,4,True,False
128,10837,tt0183659,Pollock,Pollock,0,2000,122,0,0,0,...,0,0,0,0,7.0,27765.0,6000000,8,False,False
134,10932,tt0185007,Whispers: An Elephant's Tale,Whispers: An Elephant's Tale,0,2000,72,0,0,0,...,0,0,0,0,5.1,349.0,4000000,537,False,False
236,12653,tt0213203,Rugrats in Paris,Rugrats in Paris: The Movie - Rugrats II,0,2000,78,0,1,0,...,0,0,0,0,6.2,12089.0,30000000,103,False,False
536,15978,tt0276977,Gang Tapes,Gang Tapes,0,2001,91,0,0,0,...,0,0,0,0,6.2,1075.0,50000000,60,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7694,137512,tt7921182,Dead Man's Line,Dead Man's Line,0,2018,98,0,0,0,...,0,0,0,0,7.1,369.0,10000000,1,False,False
7782,139982,tt8364508,Obscure,Obscure,0,2019,92,0,0,0,...,0,0,0,0,6.2,13.0,1000000,100000000,False,False
7961,144683,tt9260636,Bigil,Bigil,0,2019,179,0,0,0,...,1,0,0,0,7.0,18355.0,100000000,100,False,False
7983,145102,tt9358136,The Sharks,Los tiburones,0,2019,80,0,0,0,...,0,0,0,0,5.7,285.0,5000000,6,False,False
7998,145468,tt9452824,Faces of the Dead,Faces of the Dead,0,2020,110,0,0,0,...,0,0,0,0,4.9,22.0,5000000,10,False,False